-- generated by scripts/seed-commodities.ts
begin;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('GLD', 'Gold', null, 'metals', '🥇', '1 troy oz', 'oz',
  '5KMxmramuyR34buhfMe1Rdo9GmbzecGphUHi1FCDENoa', 6, 'open', 57475228::numeric / 1e6, '8hwRobKmsbS7wDp6AEm29AtfHQVgXxP1cxpMeiRksJUs', 0, 0, 4349.7)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('SLV', 'Silver', null, 'metals', '🥈', '1 troy oz', 'oz',
  '814eV7KGA4HoANZFz2xTgY7WN8dZ3Vpj1oe2P2sJkp7q', 6, 'open', 3868771278::numeric / 1e6, '5vSXVkQuZN624iCE5RkTnaBnXHNiaiuJutRSrsdZ4hqo', 0, 0, 64.62)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('XPT', 'Platinum', null, 'metals', '⚪', '1 troy oz', 'oz',
  'GXBvovSoYJ29V7zfiKcYgG7MAXSk3QxfpMpAzfUKaYBn', 6, 'open', 83240843::numeric / 1e6, '9vwkzk63MaP8o9dq6okpfqUxadcmWHSXMBMFSRaAn9bi', 0, 1, 1802)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('XPD', 'Palladium', null, 'metals', '⚫', '1 troy oz', 'oz',
  'H29hPq2orRURvNrxHGpdanteTwBKUToEuJHELb1mHTSb', 6, 'open', 113636363::numeric / 1e6, 'HAKHEn8BypJPjz9wCZX25Ey5XaHs3sBSu2DP7TsXcnCw', 0, 1, 1320)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('HG', 'Copper', null, 'metals', '🟤', '1 lb', 'lb',
  'GY8DY5A1eqWe7acMZgYdj8JGYW5RFTqckNPq3Q3Biina', 6, 'open', 38639876352::numeric / 1e6, 'FbpfhyzQsr8Wmceyrydtm5x7mtSFsWKRVnvmMeGb2n61', 0, 0, 6.47)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('BURGER', 'Flagship burger', 'Big Mac', 'fast_food', '🍔', '1 sandwich', 'sandwich',
  '8xzgCqrF2xWNjb1PJS7ncjDkFF4qm3ZxNAxRek8L85yM', 6, 'open', 4230118443::numeric / 1e6, 'Akof8jiwcEbdhCiwrAjHhGpq4SzPzqppJ9TJf7VtVkBs', 2, 4, 5.91)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('NUGGETS', '10 pc chicken nuggets', '10 pc McNuggets', 'fast_food', '🍗', '1 order', 'order',
  'CWfUMYExaJcCkt6yfDywRVKW4orBfxCU3qUL6EwHScXt', 6, 'open', 4317789291::numeric / 1e6, '3usS7AJiAEAAuheR1HShQfWACBNDZBeMEwKFXaoXQHfP', 2, 4, 5.79)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('BIGBURGER', 'Flame-grilled burger', 'Whopper', 'fast_food', '🍔', '1 sandwich', 'sandwich',
  '7wqMF7tcnAMjBLv3GxoHnn8hJUtnVT649V1XhM2suKN6', 6, 'open', 3852080123::numeric / 1e6, 'VGGFB2s2mejnUcqZmqz2w4e5JEPj628e67KWKybEC5B', 2, 4, 6.49)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('CHIXSAND', 'Chicken sandwich', 'Chick-fil-A Sandwich', 'fast_food', '🥪', '1 sandwich', 'sandwich',
  'G1YiFbcbcubC47Sb7EhSYfKJyxMwdnsZf7yFvcNncLWY', 6, 'open', 5050505050::numeric / 1e6, 'HRPRnGQeyMjmyzzdYf2AscYMppPFp8nfBZy9gokTj3kA', 2, 4, 4.95)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('TACO', 'Crunchy taco', 'Crunchy Taco', 'fast_food', '🌮', '1 taco', 'taco',
  '6jWTkcbWbQz9nH6sn3k5VJGT3MRqfkR9fCuHXsyB7LCk', 6, 'open', 13227513227::numeric / 1e6, '7qDvrionBoFbzoktj18HfVPo5EphDjWXmJW9RaERNSQu', 2, 4, 1.89)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('BURRITO', 'Chicken burrito', 'Chicken Burrito', 'fast_food', '🌯', '1 burrito', 'burrito',
  '9Wu1HFwzue5cwwjE47iCfk4PQXnSzvnHnNSUmjcjdXWa', 6, 'open', 2325581395::numeric / 1e6, 'HSYgAzmvWNh7KEq2cSEUnjdUZokCWg65z37dZPou8YjJ', 2, 4, 10.75)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('LATTE', 'Grande latte', 'Grande Latte', 'fast_food', '☕', '1 drink', 'drink',
  'HRbjve7WZxbvv4SF4LTsS8zvGwzaFGpLiTgtEbtAJGEG', 6, 'open', 4587155963::numeric / 1e6, 'Fk3KA2PygUL8p6dzf6gM7nBs8AvHNjGC8XW5fT1ghHip', 2, 4, 5.45)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('PIZZA', 'Large pepperoni pizza', 'Large Pepperoni', 'fast_food', '🍕', '1 pizza', 'pizza',
  '28x3zp9A4K33yHpw2qde9VmvW96VwjWDJjPX9x7remGR', 6, 'open', 1924557351::numeric / 1e6, '8F1uvBKhM32eA7ggKexSuAV8AqQvQs9Waif6jncFQxdn', 2, 4, 12.99)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('DBLBURGER', 'Double cheeseburger', 'Double-Double', 'fast_food', '🍔', '1 burger', 'burger',
  '6G6VhuAz2NTprHpiLfxFfBJyAbu38URnAY9NimKaCLFx', 6, 'open', 4424778761::numeric / 1e6, '7mpKMPj8Vr97x36eunEu6viYKKc7BdLErQwVJ4Jhwj1M', 2, 4, 5.65)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('BACONBRGR', 'Bacon burger', 'Baconator', 'fast_food', '🥓', '1 burger', 'burger',
  '3hgG9ueWsDMiz93o8i5eDhN2XSXqUwW4dfRDjatJvhRh', 6, 'open', 2780867630::numeric / 1e6, '4bWqT5FcExGPeWvKwnS2jJQ6UTZf745k3meJmt7QF5XM', 2, 4, 8.99)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('SPICYCHIX', 'Spicy chicken sandwich', 'Popeyes Sandwich', 'fast_food', '🌶️', '1 sandwich', 'sandwich',
  'E55Y51zUpmKF8u3VSvnfVXBAJ4yk1xzMNxFhUWKyosjw', 6, 'open', 4173622704::numeric / 1e6, 'FjMoHZkKG7QRfaP3BEn5akHXz5T1k3cKznT2LPY94F3B', 2, 4, 5.99)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('MEDCOFFEE', 'Medium coffee', 'Dunkin Medium Coffee', 'fast_food', '☕', '1 coffee', 'coffee',
  'HH9TTayNNzTDLENb4ETQW36vwW4npteQcLfQ6VwfVRYt', 6, 'open', 8361204013::numeric / 1e6, '8jutz7nXy5Tt1x4EjTff4dE1ij1YJn3XPvBWrT1QN9fP', 2, 4, 2.99)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('FRIES', 'Medium fries', 'Medium Fries', 'fast_food', '🍟', '1 order', 'order',
  'BSd8LMDtNjMfxkXQMSFHuGembyuRxzwcP23xbnED65td', 6, 'open', 6596306068::numeric / 1e6, '2zTJdArHmcSwigNEMUoj2j6qwfhRyQuo8YA5td5cJRzn', 2, 4, 3.79)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('H2O', 'California Water', null, 'water', '💧', '1 acre-foot (NQH2O)', 'af',
  'E75SHTGy6F6mKaXY2GJ8G1K4bFp2REfxQPeWzSGadPZk', 6, 'open', 55555555::numeric / 1e6, '9uinSRzXKV367gBbdMLnEeWE37ux8UW9kq54vFkPty88', 2, 4, 450)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('LAMBO', 'Italian supercar', 'Lamborghini Temerario', 'cars', '🏎️', '1 car (MSRP)', 'car',
  'AEcAjqAAKwAqetJqhM7UvL6uGrd6CSoppD5HCTpdRj4G', 6, 'open', 96153::numeric / 1e6, '2TdGLJWYGXNPhgRUGssnB9o2GtuG3FmvG4ghCEPzZ8ah', 2, 4, 260000)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('SUBMARINER', 'Rolex Submariner Date 126610LN', 'Rolex Submariner', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  'A9SAv3qXYtNqGTj8WjT1UAJYh3hMAiQDF1vss74QDmKT', 6, 'open', 1798561::numeric / 1e6, '4NGvFH1ZoW9T3bqBLxeGnvXhQjNfUtzJuaqzr9eQ3qFm', 1, 4, 13900)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('DAYTONA', 'Rolex Cosmograph Daytona 126500LN', 'Rolex Daytona', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  '8AQHK9i9whXxaac766ed9DwTNW1pZCVZAjJWUjV2iVnP', 6, 'open', 877192::numeric / 1e6, '6gyj4cLb2RWq38dGxUyJkdVDnkxBxoSQoUh3twbD9riw', 1, 4, 28500)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('GMTMASTER', 'Rolex GMT-Master II 126710BLNR', 'Rolex GMT-Master II', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  'v24QFYtynLhiEnaw4WbZsyReaTLefpJKyJNA6f7jZgR', 6, 'open', 1453488::numeric / 1e6, '8oUCxeW19AhSGw5EeYU1jqcQTx8jdnFFZwAfURkgTELT', 1, 4, 17200)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('DATEJUST', 'Rolex Datejust 41 126334', 'Rolex Datejust', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  'AGqvjSyxANHkYmfRGQPwtFuv3XCqV51mqX4zSyXCTNpe', 6, 'open', 2403846::numeric / 1e6, 'BwyK8oWb3VjTPL9HBaTd3gzYhkP6pG2GvgAjkJQYm22f', 1, 4, 10400)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('ROYALOAK', 'AP Royal Oak 15510ST', 'AP Royal Oak', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  'HqH5bLrmRqbivBT7F7ncqtT1B1MHrUbHq3biV5FLtVrL', 6, 'open', 480769::numeric / 1e6, 'HwmcVwwcefFcmHpY55oo2pXY4LSDTLaB6X785vdRgwXc', 1, 4, 52000)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('NAUTILUS', 'Patek Philippe Nautilus 5811/1G', 'Patek Nautilus', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  '4C1xtPE7Mm98E79cdawFep9STMBHyv6yR3NrNAogE4z7', 6, 'open', 195312::numeric / 1e6, 'EgbGZJpZQci8Kdooo4EZR8uK4m9BbpBpuJJ9WUhyR3cv', 1, 4, 128000)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('SANTOS', 'Cartier Santos Large WSSA0018', 'Cartier Santos', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  '8xvmfazBRw5hWTt3rgYsdT7M6yGXmnV5zBqHvTUV31BY', 6, 'open', 3424657::numeric / 1e6, 'BUWVzmKmeQmec8NaBKwoi7STFeWDGWXQy52Lx6EFcJmN', 1, 4, 7300)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('GSHOCK', 'Casio G-Shock DW-5600E', 'G-Shock DW-5600', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  '9M4Scv4JwVJpbPDCPEKbu4AzHH1TW8zcXhhLxdmn4UN7', 6, 'open', 416666666::numeric / 1e6, 'BcgS8gfcNtFBnKxa4Te3uiGuK9iRqME3QwktkFnzBQzP', 1, 4, 60)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
insert into commodities (symbol, name, display_name, category, emoji, unit, unit_short, mint, decimals, status,
  supply_cap, commodity_pubkey, oracle_kind, session_kind, last_price_usd)
values ('TISSOTPRX', 'Tissot PRX Powermatic 80', 'Tissot PRX', 'watches', '⌚', '1 watch (unworn, full set)', 'watch',
  'EK9uVKzVyY54WyHGo2CdAoFz3GsNTeeKn1qej413REne', 6, 'open', 37037037::numeric / 1e6, 'CWHY5SeWBebuyoYiBTRWhss9KdnXnLGyiR7xiRCaBZkV', 1, 4, 675)
on conflict (symbol) do update set mint = excluded.mint, supply_cap = excluded.supply_cap, commodity_pubkey = excluded.commodity_pubkey,
  oracle_kind = excluded.oracle_kind, session_kind = excluded.session_kind;
commit;
