/**
 * fee_router on localnet: config lifecycle, the permissionless `register_pool` byte-level
 * validation (positive + every negative path), vault authority checks and treasury withdrawal.
 *
 * DBC / Commodity accounts come from tests/fixtures (pre-loaded by Anchor.toml
 * [[test.validator.account]], generated by tests/fixtures/gen_fixtures.py). The claim paths that
 * CPI into Meteora need a live pool and are covered by the devnet loop, not here.
 */
import * as anchor from "@coral-xyz/anchor";
import { BN } from "@coral-xyz/anchor";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  createMint,
  getAccount,
  getAssociatedTokenAddressSync,
  getOrCreateAssociatedTokenAccount,
  mintTo,
} from "@solana/spl-token";
import { Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";

import { readFileSync } from "node:fs";
import path from "node:path";

interface FixtureKeys {
  routerPda: string;
  quoteMint: { pubkey: string; secretKey: number[] };
  baseMint: { pubkey: string; secretKey: number[] };
  creator: string;
  other: string;
  accounts: Record<string, string>;
}
const fixtures = JSON.parse(readFileSync(path.join(__dirname, "fixtures", "keys.json"), "utf8")) as FixtureKeys;

const SEED = {
  router: Buffer.from("router"),
  pool: Buffer.from("pool"),
  holderVault: Buffer.from("holder_vault"),
  buybackVault: Buffer.from("buyback_vault"),
  treasury: Buffer.from("treasury"),
};

function pda(seeds: Buffer[], programId: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(seeds, programId)[0];
}

async function expectAnchorError(p: Promise<unknown>, code: string): Promise<void> {
  let threw = false;
  try {
    await p;
  } catch (e: any) {
    threw = true;
    const got: string | undefined = e?.error?.errorCode?.code;
    const haystack = `${got ?? ""} ${e?.message ?? ""} ${(e?.logs ?? []).join("\n")} ${String(e)}`;
    expect(haystack, `expected ${code}`).to.include(code);
  }
  expect(threw, `expected transaction to fail with ${code}`).to.equal(true);
}

describe("fee_router", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const ws = anchor.workspace as any;
  const program = ws.FeeRouter as any;
  const distributorId: PublicKey = ws.Distributor.programId;
  const buybackId: PublicKey = ws.Buyback.programId;
  const pegDeskId: PublicKey = ws.PegDesk.programId;
  const connection = provider.connection;
  const admin = (provider.wallet as anchor.Wallet).payer;

  const routerPda = pda([SEED.router], program.programId);
  const quoteMint = Keypair.fromSecretKey(Uint8Array.from(fixtures.quoteMint.secretKey));
  const baseMint = Keypair.fromSecretKey(Uint8Array.from(fixtures.baseMint.secretKey));
  const fx = {
    configOk: new PublicKey(fixtures.accounts.dbc_config_ok),
    configBad: new PublicKey(fixtures.accounts.dbc_config_bad_claimer),
    poolOk: new PublicKey(fixtures.accounts.dbc_pool_ok),
    poolBad: new PublicKey(fixtures.accounts.dbc_pool_bad_claimer),
    poolWrongCfg: new PublicKey(fixtures.accounts.dbc_pool_wrong_config),
    commodity: new PublicKey(fixtures.accounts.commodity_gldx),
    creator: new PublicKey(fixtures.creator),
  };

  const keeper = Keypair.generate();
  const stranger = Keypair.generate();
  let strangerQuote: PublicKey;

  function registerAccounts(dbcPool: PublicKey, dbcConfig: PublicKey, opts: { quote?: PublicKey; base?: PublicKey; commodity?: PublicKey } = {}) {
    const quote = opts.quote ?? quoteMint.publicKey;
    const base = opts.base ?? baseMint.publicKey;
    return {
      payer: admin.publicKey,
      config: routerPda,
      dbcPool,
      dbcConfig,
      commodity: opts.commodity ?? fx.commodity,
      baseMint: base,
      quoteMint: quote,
      poolState: pda([SEED.pool, dbcPool.toBuffer()], program.programId),
      holderVault: pda([SEED.holderVault, dbcPool.toBuffer()], program.programId),
      buybackVault: pda([SEED.buybackVault, quote.toBuffer()], program.programId),
      treasuryQuote: pda([SEED.treasury, quote.toBuffer()], program.programId),
      treasuryBase: pda([SEED.treasury, base.toBuffer()], program.programId),
      routerQuoteRecv: getAssociatedTokenAddressSync(quote, routerPda, true),
      baseTokenProgram: TOKEN_PROGRAM_ID,
      quoteTokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
    };
  }

  const register = (dbcPool: PublicKey, dbcConfig: PublicKey, opts: Parameters<typeof registerAccounts>[2] = {}, feeBps = 200) =>
    program.methods.registerPool(feeBps).accountsPartial(registerAccounts(dbcPool, dbcConfig, opts)).rpc();

  before(async () => {
    for (const k of [keeper, stranger]) {
      const sig = await connection.requestAirdrop(k.publicKey, 2 * LAMPORTS_PER_SOL);
      const bh = await connection.getLatestBlockhash();
      await connection.confirmTransaction({ signature: sig, ...bh }, "confirmed");
    }
    // The fixture accounts reference these two mints by address; create them at exactly those keys.
    expect(routerPda.toBase58(), "fixtures were generated for a different fee_router id — rerun tests/fixtures/gen_fixtures.py").to.equal(fixtures.routerPda);
    await createMint(connection, admin, admin.publicKey, null, 6, quoteMint);
    await createMint(connection, admin, admin.publicKey, null, 6, baseMint);
    strangerQuote = (await getOrCreateAssociatedTokenAccount(connection, admin, quoteMint.publicKey, stranger.publicKey)).address;
  });

  it("initialize_router rejects a split that does not sum to 10_000", async () => {
    await expectAnchorError(
      program.methods
        .initializeRouter({
          distributorProgram: distributorId,
          buybackProgram: buybackId,
          pegDeskProgram: pegDeskId,
          holdersBps: 5_000,
          buybackBps: 2_500,
          protocolBps: 2_499,
        })
        .accountsPartial({ payer: admin.publicKey, config: routerPda, systemProgram: SystemProgram.programId })
        .rpc(),
      "InvalidSplit",
    );
  });

  it("initialize_router stores the 50/25/25 split and program ids", async () => {
    await program.methods
      .initializeRouter({
        distributorProgram: distributorId,
        buybackProgram: buybackId,
        pegDeskProgram: pegDeskId,
        holdersBps: 5_000,
        buybackBps: 2_500,
        protocolBps: 2_500,
      })
      .accountsPartial({ payer: admin.publicKey, config: routerPda, systemProgram: SystemProgram.programId })
      .rpc();
    const cfg = await program.account.routerConfig.fetch(routerPda);
    expect(cfg.admin.equals(admin.publicKey)).to.equal(true);
    expect(cfg.holdersBps).to.equal(5_000);
    expect(cfg.buybackBps).to.equal(2_500);
    expect(cfg.protocolBps).to.equal(2_500);
    expect(cfg.pegDeskProgram.equals(pegDeskId)).to.equal(true);
    expect(cfg.keeperCount).to.equal(0);
    expect(cfg.paused).to.equal(false);
  });

  it("admin-only: set_split, set_keepers, pause", async () => {
    const adminOnly = (signer: Keypair) => ({ admin: signer.publicKey, config: routerPda });
    await expectAnchorError(
      program.methods.setSplit(6_000, 2_000, 2_000).accountsPartial(adminOnly(stranger)).signers([stranger]).rpc(),
      "Unauthorized",
    );
    await expectAnchorError(program.methods.setSplit(6_000, 2_000, 2_001).accountsPartial(adminOnly(admin)).rpc(), "InvalidSplit");
    await program.methods.setSplit(6_000, 2_000, 2_000).accountsPartial(adminOnly(admin)).rpc();
    await program.methods.setSplit(5_000, 2_500, 2_500).accountsPartial(adminOnly(admin)).rpc();

    await expectAnchorError(
      program.methods
        .setKeepers(Array.from({ length: 9 }, () => Keypair.generate().publicKey))
        .accountsPartial(adminOnly(admin))
        .rpc(),
      "TooManyKeepers",
    );
    await program.methods.setKeepers([keeper.publicKey]).accountsPartial(adminOnly(admin)).rpc();
    let cfg = await program.account.routerConfig.fetch(routerPda);
    expect(cfg.keeperCount).to.equal(1);
    expect(cfg.keepers[0].equals(keeper.publicKey)).to.equal(true);

    await program.methods.pause(true).accountsPartial(adminOnly(admin)).rpc();
    cfg = await program.account.routerConfig.fetch(routerPda);
    expect(cfg.paused).to.equal(true);
    // registration is refused while paused
    await expectAnchorError(register(fx.poolOk, fx.configOk), "Paused");
    await program.methods.pause(false).accountsPartial(adminOnly(admin)).rpc();
  });

  it("register_pool refuses a config whose fee_claimer is not the router PDA", async () => {
    await expectAnchorError(register(fx.poolBad, fx.configBad), "FeeClaimerMismatch");
  });

  it("register_pool refuses a pool that points at a different config", async () => {
    // pool says config = configBad, we pass configOk (fee_claimer ok) → ConfigMismatch
    await expectAnchorError(register(fx.poolWrongCfg, fx.configOk), "ConfigMismatch");
  });

  it("register_pool refuses a quote mint that differs from the config's", async () => {
    const otherMint = await createMint(connection, admin, admin.publicKey, null, 6);
    await expectAnchorError(register(fx.poolOk, fx.configOk, { quote: otherMint }), "QuoteMintMismatch");
  });

  it("register_pool refuses a base mint that differs from the pool's", async () => {
    const otherMint = await createMint(connection, admin, admin.publicKey, null, 6);
    await expectAnchorError(register(fx.poolOk, fx.configOk, { base: otherMint }), "BaseMintMismatch");
  });

  it("register_pool refuses a commodity not owned by peg_desk or with another coin mint", async () => {
    // any non-peg_desk-owned account (a system account)
    await expectAnchorError(register(fx.poolOk, fx.configOk, { commodity: stranger.publicKey }), "InvalidCommodity");
  });

  it("register_pool refuses accounts not owned by the DBC program", async () => {
    await expectAnchorError(register(stranger.publicKey, fx.configOk), "InvalidDbcAccount");
    await expectAnchorError(register(fx.poolOk, stranger.publicKey), "InvalidDbcAccount");
  });

  it("register_pool refuses fee_bps above MAX_FEE_BPS", async () => {
    await expectAnchorError(register(fx.poolOk, fx.configOk, {}, 1_001), "InvalidFeeBps");
  });

  it("register_pool (permissionless) accepts the valid fixture and creates every vault", async () => {
    await register(fx.poolOk, fx.configOk);
    const a = registerAccounts(fx.poolOk, fx.configOk);
    const ps = await program.account.poolState.fetch(a.poolState);
    expect(ps.dbcPool.equals(fx.poolOk)).to.equal(true);
    expect(ps.dbcConfig.equals(fx.configOk)).to.equal(true);
    expect(ps.baseMint.equals(baseMint.publicKey)).to.equal(true);
    expect(ps.quoteMint.equals(quoteMint.publicKey)).to.equal(true);
    expect(ps.commodity.equals(fx.commodity)).to.equal(true);
    expect(ps.creator.equals(fx.creator), "creator read from VirtualPool bytes").to.equal(true);
    expect(ps.feeBps).to.equal(200);
    expect(ps.migrated).to.equal(false);
    expect(ps.totalClaimed.toNumber()).to.equal(0);

    for (const [name, key, owner] of [
      ["holder_vault", a.holderVault, a.poolState],
      ["buyback_vault", a.buybackVault, routerPda],
      ["treasury[quote]", a.treasuryQuote, routerPda],
      ["router_quote_recv", a.routerQuoteRecv, routerPda],
    ] as const) {
      const acc = await getAccount(connection, key);
      expect(acc.mint.equals(quoteMint.publicKey), `${name} mint`).to.equal(true);
      expect(acc.owner.equals(owner), `${name} authority`).to.equal(true);
    }
    const tb = await getAccount(connection, a.treasuryBase);
    expect(tb.mint.equals(baseMint.publicKey)).to.equal(true);
    expect(tb.owner.equals(routerPda)).to.equal(true);

    // second registration of the same pool fails (PoolState already exists)
    let threw = false;
    try {
      await register(fx.poolOk, fx.configOk);
    } catch {
      threw = true;
    }
    expect(threw).to.equal(true);
  });

  it("register_pool_admin skips layout checks but is admin-only", async () => {
    // bad-claimer pool: permissionless path fails, admin override succeeds
    const accounts = registerAccounts(fx.poolBad, fx.configBad);
    await expectAnchorError(
      program.methods
        .registerPoolAdmin(100, fx.creator)
        .accountsPartial({ ...accounts, payer: stranger.publicKey })
        .signers([stranger])
        .rpc(),
      "Unauthorized",
    );
    await program.methods.registerPoolAdmin(100, fx.creator).accountsPartial(accounts).rpc();
    const ps = await program.account.poolState.fetch(accounts.poolState);
    expect(ps.creator.equals(fx.creator)).to.equal(true);
    expect(ps.feeBps).to.equal(100);
  });

  it("withdraw_for_epoch / withdraw_for_buyback only accept the sibling programs' PDA signers", async () => {
    const a = registerAccounts(fx.poolOk, fx.configOk);
    await mintTo(connection, admin, quoteMint.publicKey, a.holderVault, admin, 1_000_000);
    await mintTo(connection, admin, quoteMint.publicKey, a.buybackVault, admin, 1_000_000);

    await expectAnchorError(
      program.methods
        .withdrawForEpoch(new BN(1))
        .accountsPartial({
          distAuthority: stranger.publicKey,
          config: routerPda,
          poolState: a.poolState,
          holderVault: a.holderVault,
          quoteMint: quoteMint.publicKey,
          destination: strangerQuote,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([stranger])
        .rpc(),
      "InvalidAuthority",
    );
    await expectAnchorError(
      program.methods
        .withdrawForBuyback(new BN(1))
        .accountsPartial({
          bbAuthority: stranger.publicKey,
          config: routerPda,
          coinMint: quoteMint.publicKey,
          buybackVault: a.buybackVault,
          destination: strangerQuote,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([stranger])
        .rpc(),
      "InvalidAuthority",
    );
    // even the admin cannot pull from the holder vault directly
    await expectAnchorError(
      program.methods
        .withdrawForEpoch(new BN(1))
        .accountsPartial({
          distAuthority: admin.publicKey,
          config: routerPda,
          poolState: a.poolState,
          holderVault: a.holderVault,
          quoteMint: quoteMint.publicKey,
          destination: strangerQuote,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .rpc(),
      "InvalidAuthority",
    );
    expect(Number((await getAccount(connection, a.holderVault)).amount)).to.equal(1_000_000);
    expect(Number((await getAccount(connection, a.buybackVault)).amount)).to.equal(1_000_000);
  });

  it("withdraw_treasury moves protocol revenue and is admin-only", async () => {
    const a = registerAccounts(fx.poolOk, fx.configOk);
    await mintTo(connection, admin, quoteMint.publicKey, a.treasuryQuote, admin, 500_000);
    const adminQuote = (await getOrCreateAssociatedTokenAccount(connection, admin, quoteMint.publicKey, admin.publicKey)).address;

    const accounts = {
      admin: admin.publicKey,
      config: routerPda,
      mint: quoteMint.publicKey,
      treasury: a.treasuryQuote,
      destination: adminQuote,
      tokenProgram: TOKEN_PROGRAM_ID,
    };
    await expectAnchorError(
      program.methods.withdrawTreasury(new BN(1)).accountsPartial({ ...accounts, admin: stranger.publicKey, destination: strangerQuote }).signers([stranger]).rpc(),
      "Unauthorized",
    );
    await expectAnchorError(program.methods.withdrawTreasury(new BN(0)).accountsPartial(accounts).rpc(), "ZeroAmount");
    await expectAnchorError(program.methods.withdrawTreasury(new BN(500_001)).accountsPartial(accounts).rpc(), "InsufficientVault");
    await program.methods.withdrawTreasury(new BN(200_000)).accountsPartial(accounts).rpc();
    expect(Number((await getAccount(connection, a.treasuryQuote)).amount)).to.equal(300_000);
    expect(Number((await getAccount(connection, adminQuote)).amount)).to.equal(200_000);
  });

  it("set_programs rotates the admin (and back)", async () => {
    const newAdmin = Keypair.generate();
    await program.methods
      .setPrograms(distributorId, buybackId, pegDeskId, newAdmin.publicKey)
      .accountsPartial({ admin: admin.publicKey, config: routerPda })
      .rpc();
    await expectAnchorError(
      program.methods.pause(true).accountsPartial({ admin: admin.publicKey, config: routerPda }).rpc(),
      "Unauthorized",
    );
    // rotate back (newAdmin signs; fee payer is still the provider wallet)
    await program.methods
      .setPrograms(distributorId, buybackId, pegDeskId, admin.publicKey)
      .accountsPartial({ admin: newAdmin.publicKey, config: routerPda })
      .signers([newAdmin])
      .rpc();
    const cfg = await program.account.routerConfig.fetch(routerPda);
    expect(cfg.admin.equals(admin.publicKey)).to.equal(true);
  });
});
